### ISSUE TITLE
Fix padding on homepage

### ISSUE THREAD

**Issue by signalnerve** [byteconf/byteconf.com#10]
it's a little crowded my dude

<img width="512" alt="screen shot 2018-12-09 at 11 41 57 am" src="https://user-images.githubusercontent.com/922353/49701269-707ab400-fba7-11e8-983f-6831defcdbf9.png">

**Comment by fmmricardo** [comment]
Hi @signalnerve, I'm waiting for permission.

**Comment by soulchainer** [comment]
Hey, buddies :D.

Seems like you already solved this with https://github.com/byteconf/byteconf.com/pull/16.
But you forgot to close the issue xD.
This doesn't happen if, when you create a PR or a commit, @fmmricardo, you use some standard keywords that are available for that. Read → https://help.github.com/en/articles/closing-issues-using-keywords ;).
That way, when the PR is merged, the associated issues are closed automatically :D.

**Comment by signalnerve** [comment]
indeed, this is fixed! thanks @soulchainer
